### ISSUE TITLE
Create the PDM/PBS/AOA/WBS Charts

### ISSUE THREAD

**Issue by m-asjedh** [SPPM-GP-15/LLH-docs#12]

**Comment by RavinduLaksahan** [comment]
[AOA](https://drive.google.com/file/d/1_Txea67AgG8jcsHiytmoeorD3unj5ywq/view?usp=drive_link)
[PDM](https://drive.google.com/file/d/1gIof1VOXpVGoOHZWwt2-3fnhJhK-fITK/view?usp=drive_link)
[WBS](https://drive.google.com/file/d/17giNtgP4EqVOtQJnL0Loj2sUAxPepxRg/view?usp=drive_link)
[PBS](https://drive.google.com/file/d/1qZqPvXhnqD8j8PD1_85UaXL2uDDG-2sl/view?usp=drive_link)
