### ISSUE TITLE
Create the SRS - V1 document

### ISSUE THREAD

**Issue by m-asjedh** [SPPM-GP-15/LLH-docs#14]

**Comment by m-asjedh** [comment]
SRS :[SRS Document]( https://drive.google.com/drive/u/0/folders/1zV3oCG7BTr6TyDYJs8gPuTdAjkA3LgFs)

**Comment by RavinduLaksahan** [comment]
[SRS V1](https://drive.google.com/file/d/1yAAPlUFOApZZvdaGjX2ChnTWRdrbqCgY/view?usp=drive_link)
