### ISSUE TITLE
Create the communication plan V2

### ISSUE THREAD

**Issue by m-asjedh** [SPPM-GP-15/LLH-docs#16]

**Comment by m-ahmed-anwer** [comment]
Communication plan - https://docs.google.com/document/d/1R2IR6NIC4lFQ85V1aqd2LL7Ivi-s3zfV/edit?usp=drive_link&ouid=116596449140343010182&rtpof=true&sd=true

**Comment by RavinduLaksahan** [comment]
[](https://docs.google.com/document/d/1XN4tGtAo8sO8m7YH0vnMYKJFj6wYzUTk/edit?usp=drive_link&ouid=110724999248625699426&rtpof=true&sd=true)
