### ISSUE TITLE
Develop Project Plan

### ISSUE THREAD

**Issue by m-asjedh** [SPPM-GP-15/LLH-docs#2]
Define project scope
Conduct client interviews
Identify Stakeholders
Send the client the project acceptance letter

**Comment by m-ahmed-anwer** [comment]
Project Plan - https://docs.google.com/document/d/1l6bLPxsfBq3NTAwebBKk1ZTwlthraMvP/edit?usp=drive_link&ouid=116596449140343010182&rtpof=true&sd=true
