### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by m-asjedh** [SPPM-GP-15/LLH-docs#34]
Create the Lanka hardware hub user manual document

**Comment by m-asjedh** [comment]
[User Manual](https://drive.google.com/drive/u/0/folders/1wnir85aGesE_vxbFgJJCpdKyuab8jgg2)

**Comment by m-ahmed-anwer** [comment]
Link - https://drive.google.com/file/d/1eo8PZQIX-nZ_2DJ5qbgC_fk4dWkmVfry/view?usp=drive_link
